### PR TITLE
Load queries at runtime and remove temporal-system from the list of namespaces

### LINKED ISSUE #291: Clicking on "Stack Trace" on a completed workflow does nothing
Screen Shot 2022-03-07 at 12 11 11 PM

trying to click on "Stack Trace" it does not change the blue underline to see that it did anything
could be some indicator that there is no stack trace for a closed workflow exec

### PR DESCRIPTION
**Pull request by stevekinney**
Fixes issue where the UI would crash if a worker was not running when fetching stack traces or queries.

Fixes #291 and #308.

### CODE REVIEW

File: src/lib/utilities/request-from-api.ts [hunk 1]
```diff
@@ -87,14 +89,18 @@ export const requestFromAPI = async <T>(
...
-    if (shouldRetry && retryCount > 0) {
-      return new Promise((resolve) => {
-        setTimeout(() => {
-          resolve(requestFromAPI(endpoint, init, retryCount - 1));
-        }, retryInterval);
-      });
+    if (notifyOnError) {
+      handleError(error);
+
+      if (shouldRetry && retryCount > 0) {
```
Comment (feedmeapples) [inline src/lib/utilities/request-from-api.ts:95]: why retrying depends on notifyOnError being true?

File: src/routes/namespaces/[namespace]/workflows/[workflow]/[run]/stack-trace.svelte [hunk 2]
```diff
@@ -30,37 +24,53 @@
...
+    stackTrace = getWorkflowStackTrace({
       workflow,
       namespace,
     });
 
-    isLoading = false;
-    currentdate = new Date();
+    stackTrace.then(() => {
+      currentdate = new Date();
+    });
```
Comment (GiantRobots) [inline src/routes/namespaces/[namespace]/workflows/[workflow]/[run]/stack-trace.svelte:48]: This could be await if we update the methods to be async. But I don't think there's a lot of value in that. Just throwing it out there.

**Review by GiantRobots — APPROVED** [review]
