### PR TITLE
Nexus

### LINKED ISSUE #2149: Bad performance due to gRPC-connection-per-request
**Describe the bug**

The UI server creates a gRPC client connection for each request.
https://github.com/temporalio/ui/blob/0108a5762a84464e99e6919644c9276f4f264847/server/server/api/handler.go#L77-L101

This is bad for performance. It is recommended to have a single gRPC connection for the lifetime of the application (the same way it is recommended to have a single temporal client for the lifetime of the application).

I ran some benchmarks with 500 requests (100 concurrent requests).

```sh
hey -n 500 -c 100 'http://localhost:8080/api/v1/namespaces' > /tmp/one-client.txt
```

Here are the results.

<details>
<summary>Connection-per-request (current implementation)</summary>
<br>

```
Summary:
  Total:        23.8720 secs
  Slowest:      18.6736 secs
  Fastest:      0.7964 secs
  Average:      3.3815 secs
  Requests/sec: 20.9451
  

Response time histogram:
  0.796 [1]     |
  2.584 [261]   |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  4.372 [114]   |■■■■■■■■■■■■■■■■■
  6.160 [76]    |■■■■■■■■■■■■
  7.947 [13]    |■■
  9.735 [16]    |■■
  11.523 [5]    |■
  13.310 [4]    |■
  15.098 [2]    |
  16.886 [0]    |
  18.674 [8]    |■


Latency distribution:
  10% in 1.0995 secs
  25% in 1.4034 secs
  50% in 2.3972 secs
  75% in 4.2975 secs
  90% in 6.0804 secs
  95% in 8.8946 secs
  99% in 17.9976 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0052 secs, 0.7964 secs, 18.6736 secs
  DNS-lookup:   0.0016 secs, 0.0000 secs, 0.0396 secs
  req write:    0.0010 secs, 0.0000 secs, 0.0380 secs
  resp wait:    3.3748 secs, 0.7962 secs, 18.6359 secs
  resp read:    0.0003 secs, 0.0000 secs, 0.0023 secs

Status code distribution:
  [200] 500 responses
```

</details>

<details>
<summary>Single gRPC connection for the lifetime of the application</summary>
<br>

```
Summary:
  Total:        8.7794 secs
  Slowest:      5.6887 secs
  Fastest:      0.2492 secs
  Average:      1.5338 secs
  Requests/sec: 56.9512
  

Response time histogram:
  0.249 [1]     |
  0.793 [139]   |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  1.337 [125]   |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  1.881 [96]    |■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  2.425 [59]    |■■■■■■■■■■■■■■■■■
  2.969 [25]    |■■■■■■■
  3.513 [22]    |■■■■■■
  4.057 [8]     |■■
  4.601 [17]    |■■■■■
  5.145 [5]     |■
  5.689 [3]     |■


Latency distribution:
  10% in 0.4974 secs
  25% in 0.7003 secs
  50% in 1.3042 secs
  75% in 1.9413 secs
  90% in 3.1785 secs
  95% in 4.0926 secs
  99% in 4.8942 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0067 secs, 0.2492 secs, 5.6887 secs
  DNS-lookup:   0.0011 secs, 0.0000 secs, 0.0470 secs
  req write:    0.0008 secs, 0.0000 secs, 0.0358 secs
  resp wait:    1.5257 secs, 0.2489 secs, 5.6884 secs
  resp read:    0.0005 secs, 0.0000 secs, 0.0042 secs

Status code distribution:
  [200] 500 responses
```

</details>

I am happy to create a PR if the proposed solution is acceptable. I am already running it in production at my company.

### PR DESCRIPTION
**Pull request by Alex-Tideman**
## Description & motivation 💭 
UI to support for listing, searching, creating, editing and deleting of Nexus Endpoints

New top-level navigation to Nexus pages on navigation with a NexusGuard to show. The flag for showing Nexus from server is `systemInfo.capabilities.nexus = true`.

Nexus endpoints for OSS will allow any namespace in cluster to be Target and all namespaces in the cluster will be allowed caller namespaces. The architecture of loading data is different than the rest of the app in that I'm using load functions so we can have a clean split of APIs from OSS vs Cloud.

The event history has also been updated to handle and display Nexus events.

Also as part of this PR, the api has been updated to handle both /api/v1 and none prefix api routes. This way we can keep the current client-side route-for-api path and later move to non-prefixed routes.

Things not included in PR but will come soon:
- PendingNexusOperations - need server/api support to link these to event history.
- Nexus Callbacks
- Displaying endpoint descriptions as Markdown

### Screenshots (if applicable) 📸 
Screenshot 2024-07-11 at 1 08 26 PM
Screenshot 2024-07-11 at 1 06 43 PM
Screenshot 2024-07-11 at 1 06 56 PM
Screenshot 2024-07-11 at 1 07 28 PM
Screenshot 2024-07-11 at 1 07 51 PM
Screenshot 2024-07-11 at 1 08 02 PM
Screenshot 2024-07-11 at 1 09 39 PM

### How was this tested 👻 

- [x] Manual testing
- [ ] E2E tests added
- [x] Unit tests added

### Issue(s) closed 

Fixes #2149

### CODE REVIEW

**Review by rossedfort — APPROVED** [review]

File: src/lib/holocene/markdown.svelte [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+<div class={className}>
+  <Label {required} hidden={labelHidden} {label} for={id} />
+  {#if description}
+    <p class="pb-2 text-sm">{description}</p>
+  {/if}
+  <div class="relative mt-2">
+    <textarea
+      bind:value
+      class={merge(
+        'surface-input min-h-fit w-full rounded-lg border-2 border-subtle px-3 py-2 font-mono text-sm focus-visible:border-information focus-visible:shadow-[0_0_0_4px_rgb(97,115,243,0.7)] focus-visible:outline-none enabled:hover:border-information',
```
Comment (rossedfort) [inline src/lib/holocene/markdown.svelte:47]: Follow up task - create a tailwind util for this arbitrary shadow class: https://tailwindcss.com/docs/box-shadow#customizing-your-theme

File: src/lib/holocene/select/multi-select.svelte [hunk 2]
```diff
@@ -27,9 +27,15 @@
   export let selectAllLabel: string;
   export let clearAllLabel: string;
   export let active = false;
+  export let disabled = false;
   export let position: 'left' | 'right' = 'left';
+  export let initialSelectedAll = true;
```
Comment (rossedfort) [inline src/lib/holocene/select/multi-select.svelte:32]: Follow-up: I'm not actually sure if this is the default we want. IMO a multi-select should start with none selected. Also, if we already have an `initialSelected` prop, can't the Cloud page just pass that prop in as the whole list of namespaces?

File: src/lib/pages/nexus-empty-state.svelte
Comment (rossedfort) [inline src/lib/pages/nexus-empty-state.svelte:1]: Follow-up: no i18n on this file

File: src/lib/holocene/markdown.svelte (hunk 1 above)
Comment (Alex-Tideman) [reply src/lib/holocene/markdown.svelte:47]: Most certainly going to delete this anyways when we get proper Markdown

File: src/lib/pages/nexus-edit-endpoint.svelte [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+    </div>
+  </div>
+  <NexusForm {endpoint} {namespaceList} {error} {isCloud} nameDisabled />
+  <div class="flex items-center gap-4">
+    <Button on:click={onUpdate} {loading}>{translate('common.save')}</Button>
+    <Button
+      variant="ghost"
+      on:click={() => goto(routeForNexusEndpoint($page.params.id))}
+      >{translate('common.cancel')}</Button
+    >
```
Comment (rossedfort) [inline src/lib/pages/nexus-edit-endpoint.svelte:56]: Follow-up: this should probably be a link

File: src/lib/pages/nexus-endpoint.svelte
Comment (rossedfort) [inline src/lib/pages/nexus-endpoint.svelte:1]: Follow-up: i18n

File: src/lib/pages/nexus-form.svelte [hunk 4]
```diff
@@ -0,0 +1,176 @@
...
+  </IsOssGuard>
+  <Markdown
+    label={translate('common.description')}
+    description={translate('nexus.nexus-description')}
+    bind:value={description}
+    id="description"
+    placeholder={translate('nexus.description-placeholder')}
+  >
+    <p class="text-xs text-secondary" slot="info">
+      Do not include sensitive data.
```
Comment (rossedfort) [inline src/lib/pages/nexus-form.svelte:169]: Follow-up: i18n

File: src/lib/holocene/select/multi-select.svelte (hunk 2 above)
Comment (Alex-Tideman) [reply src/lib/holocene/select/multi-select.svelte:32]: It's a bit tricky, because all our other multi-selects we want all selected because they are filters (include all filters...then remove them).

I'll follow up with something better here for sure.

File: src/routes/(app)/nexus/+layout.svelte [hunk 5]
```diff
@@ -0,0 +1,13 @@
+<script>
+  import NexusGuard from '$lib/components/nexus-guard.svelte';
+</script>
+
+<NexusGuard>
+  <div slot="fallback">
+    <p>
+      Sorry, this feature is not available in this version of Temporal. Please
+      enable Nexus or upgrade to a newer version.
```
Comment (rossedfort) [inline src/routes/(app)/nexus/+layout.svelte:9]: Follow-up: i18n
